apiVersion: v1
kind: Service
metadata:
  name: trigger
  labels:
    app.kubernetes.io/name: trigger
spec:
  selector:
    app.kubernetes.io/name: trigger
  ports:
    - name: http
      port: 3000
      targetPort: http
