apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: the-company
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: the-company
automountServiceAccountToken: false
