apiVersion: v1
kind: ServiceAccount
metadata:
  name: core
  namespace: the-company
  labels:
    app.kubernetes.io/name: core
    app.kubernetes.io/part-of: the-company
automountServiceAccountToken: false
