apiVersion: v1
kind: ServiceAccount
metadata:
  name: openfga
  namespace: the-company
  labels:
    app.kubernetes.io/name: openfga
    app.kubernetes.io/part-of: the-company
automountServiceAccountToken: false
